version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      environment:
       KAFKA_ZOOKEEPER_CONNECT = zookeeper:2181
       KAFKA_ADVERTISED_HOST_NAME = localhost
       
    depends_on:
      - zookeeper
